version: "3.8"
services:
  mysqldb:
    image: mysql:8.0
    build:
      context: .               # Dockerfileへのパス指定
      dockerfile: Dockerfile   # Dockerfileへのパス指定
    container_name: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_USER=$MYSQLDB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql 
      - ./sql:/docker-entrypoint-initdb.d 
    networks:
      - mynetwork
  java:
    image: openjdk:15
    container_name: java
    env_file:
      - ./.env # mysqlと同じものを指定
    tty: true
    working_dir: /app
    volumes:
      - .:/app # Spring Bootのプロジェクト
    ports:
      - 8080:8080 # 通常実行
      - 5050:5050 # デバッグ用
    depends_on:
      - mysqldb # 「mysql」の後で起動
    networks:
      - mynetwork

volumes:
  db:

networks:
  mynetwork:
    driver: bridge
