spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gallery?useUnicode=true
    username: gallery
    password: gallery
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: hashimoto.osamu
    password: **** **** **** ****
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
